version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/pms-pst-pensioner-details-taskdef:1"
        LoadBalancerInfo:
          ContainerName: "pst-process-detail-container"
          ContainerPort: "8082"
        PlatformVersion: "LATEST"
